name: flutter_counter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  bloc: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_lints: ^1.0.4

dev_dependencies:
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^0.1.0
  test: ^1.16.0

flutter:
  uses-material-design: true
